### ISSUE TITLE
English Version

### ISSUE THREAD

**Issue by anhkhoa14592** [demonsec666/secist_script#1]
Hi demonsec666,
I'm very interested in this project. i'm trying to test but there aren't any English version and it makes me too hard to use. So, please make English version then i think many people can try it :).
By the way, thanks for your project 👍

**Comment by demonsec666** [comment]
thank you very much! In the next day, I will proceed to develop the English version, thank you for your suggestions

**Comment by demonsec666** [comment]
@anhkhoa14592  HI MAN:
Thanks for your suggestions and reminders, we have uploaded the English version. If there is a problem in the message below, we are trying to learn, where I only said on behalf of my and my little partner, Thanks!            https://github.com/demonsec666/secist_script
